language: c
branches:
  except:
  - "/^feature.*$/"
  - "/^fix.*$/"
  - "gh-pages"
git:
  depth: 9999999
matrix:
  include:

# Coverity build, must be the first!
  - os: linux
    dist: xenial
    compiler: gcc
    sudo: required
    env:
    - MATRIX_EVAL="-DCIO_CTEST_TOOLCHAIN_FILE:STRING=$TRAVIS_BUILD_DIR/cmake/gcc5.cmake -DCIO_CTEST_CONFIGURATION_TYPE:STRING=Debug -DCIO_CTEST_COVERAGE:BOOL=OFF"
    addons:
      coverity_scan:
        project:
          name: gatzka/cio
          description: Build submitted via Travis CI
        notification_email: stephan.gatzka@gmail.com
        build_script_url: https://raw.githubusercontent.com/gatzka/cio/coverity_scan/.travisci_build_coverity_scan.sh
        build_command_prepend: cmake -DCMAKE_C_COMPILER:STRING=gcc -DCMAKE_CXX_COMPILER:STRING=g++ -DCMAKE_BUILD_TYPE:STRING=Debug ./
        build_command: make -j
        branch_pattern: coverity_scan
      apt:
        packages:
        - cmake
        - cmake-data
        - libbsd-dev
        - ninja-build

